account/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('user_login.urls')),
    path('country/',include('country.urls')),
    # path('sentry-debug/', trigger_error),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

country/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from country import views


app_name = 'country'
urlpatterns = [
    path('',views.index,name='index'),
    path('country/<int:country_id>/',views.details,name='details'),
    path('add/',views.add_country,name='add_country'),
    path('edit/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

    path('country-rest/',views.CountryListView.as_view(),name="list_country"),
    path('country-rest/<int:pk>',views.CountryDetailView.as_view(),name="detail_country"),
    
]

user_login/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from .import views

app_name='user_login'

urlpatterns = [
    path('signup/',views.signup_view,name='signup_view'),
    path('login/',views.login_view,name='login_view'),
    path('logout/',views.logout_view,name='logout_view'),
]

country/models.py
from django.db import models

# Create your models here.


class country(models.Model):

    def __str__(self):
        return self.country_name


    country_name = models.CharField(max_length=50)
    currency = models.CharField(max_length=50)
    country_image = models.ImageField(default='default.jpg',upload_to='country_image/')
    created_at = models.DateTimeField(auto_now_add=True)

user_login/models.py
from django.db import models

# Create your models here.

country/forms.py
from django import forms
from .models import country

class countryForm(forms.ModelForm):
    class Meta:

        model = country
        fields = ['country_name','currency','country_image']

country/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from country.models import country
from .forms import countryForm
from django.contrib.auth.decorators import login_required
from rest_framework import generics,status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .models import country
from .serializers import CountrySerializer

# Create your views here.

def index(request):
    country_list = country.objects.all()
    context ={
        'country_list':country_list
    }
    return render(request,'country/index.html',context)

def details(request,country_id):
    countrys = country.objects.get(id=country_id)
    return render(request,'country/details.html',{'country':countrys})

@login_required(login_url="/account/login/")
def add_country(request):
    if request.method == "POST":
        country_name=request.POST.get('country_name',)
        currency=request.POST.get('currency',)
        country_image=request.FILES['country_image']

        countrys = country(country_name=country_name,currency=currency,country_image=country_image)
        countrys.save()

    return render(request,'country/add_country.html')

def update(request,id):
    countrys = country.objects.get(id=id)
    form = countryForm(request.POST or None, request.FILES, instance=countrys)
    if form.is_valid():
        form.save()
        return redirect('/country')
    return render(request,'country/edit.html',{'form':form,'country':countrys})

def delete(request,id):
    if request.method == "POST":
        countrys=country.objects.get(id=id)
        countrys.delete()
        return redirect('/country')
    return render(request,'country/delete.html')




class CountryListView(generics.ListCreateAPIView):
    queryset = country.objects.all()
    serializer_class = CountrySerializer
class CountryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = country.objects.all()
    serializer_class = CountrySerializer
@api_view(['GET','POST','PATCH','PUT','DELETE'])
def saveCountry(request):
    if request.method =="POST":
        saveSerialize = CountrySerializer(data=request.data)
        if saveSerialize.is_valid():
            saveSerialize.save()
            return Response(saveSerialize.data,status=status.HTTP_201_CREATED)
            return Response(saveSerialize.data,status=status.HTTP_400_BAD_REQUEST)

user_login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('/country')
    else:
        form = UserCreationForm()
    return render(request,"user_login/signup.html",{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('/country')
    else:
        form = AuthenticationForm()
    return render(request,"user_login/login.html",{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/country')

country/templates/country/add_country.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="country_name" id="name" placeholder="Enter Country Name"><br>
    <input type="text" name="currency" id="price" placeholder="Enter currency"><br>
    <input type="file" name="country_image" id="country_image"><br>
    
    <input type="submit" name="submit" id="submit">
</form>

country/templates/country/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <title>Countries</title>
</head>
<body>
    <!-- As a heading -->
  <nav class="navbar navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">Countries</span>
  </nav>


  {% block body %}

  {% endblock %}
</body>
</html>

country/templates/country/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure to delete?
    <input type="submit">
</form>

country/templates/country/details.html
{% extends 'country/base.html' %}
  
{% block body %}

<div class="container">
   
<div class="card" style="width: 30rem;">
       
    <div class="card-body">
        <div class="row">
          <div class="col-sm-6">
            <img class="card-img" src="{{country.country_image.url}}" alt="Card image cap">
           </div>
         <div class="col-sm-6">

            <br>
        Country Name: {{country.country_name}}<br>
        Currency: {{country.currency}}<br><br>
        <a class ="btn btn-warning" href="{% url 'country:update' country.id %}">Update</a>
        <a class ="btn btn-danger" href="{% url 'country:delete' country.id %}">DELETE</a>
          

        </div>  
        </div>  
    </div>
 </div>

{% endblock %}

country/templates/country/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="submit" placeholder="UPDATE">
</form>

country/templates/country/index.html
{% extends 'country/base.html' %}
  
  {% block body %}

  <div class="container">
    
      {% for country in country_list %}
      <!-- <div class="col-md-3">
        <div class="card">
          <img src="{{country.country_image.url}}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{country.country_name}}</h5>
            <p class="card-text">{{country.currency}}</p>
            <a href="{% url 'country:details' country.id %}">View Details</a>
          </div>
        </div>
      </div> -->

      <div class="card" style="width: 30rem;">
       
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                <img class="card-img" src="{{country.country_image.url}}" alt="Card image cap">
                </div>
                <div class="col-sm-6">
               <h2 class="card-title">{{country.country_name}}</h2>
                <p class="card-text">{{country.currency}}</p>
               <!-- <small>Current date and time:23rd jan 2020, 14.34</small> -->
               <a href="#" class="btn btn-outline-primary">Show Map</a> &nbsp;
               <a href="{% url 'country:details' country.id %}" class="btn btn-outline-primary">Details</a>
               <!-- <a href="{% url 'country:details' country.id %}" class="btn btn-outline-primary">View Details</a> -->
                </div>  
            </div>  
        </div>
     </div>
      {% endfor %}
    </div>
  </div>

  
   
        <!-- {{country.id}} -- {{country.name}}<br> -->
        <!-- <a href="/country/{{country.id}}">{{country.name}}</a><br> -->
        
   
  {% endblock %}

user_login/templates/user_login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <title>Document</title>
</head>
<body>
    <!-- As a heading -->
  <nav class="navbar navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">Logout</span>
  </nav>
  <nav>
      <form class="logout-link" action="{% url 'account:logout_view' %}" method="POST">
          {% csrf_token %}
          <button type="submit">
                Logout
          </button>
      </form>
  </nav>


  {% block body %}

  {% endblock %}
</body>
</html>

user_login/templates/user_login/index.html
{% load socialaccount %}
<html>
  <head>
    <title>Google Registration</title>
  </head>
  <body>
  <h1>My Google Login Project</h1>
  {% if user.is_authenticated %}
  <p>Welcome, {{ user.username }} !</p>
 
  {% else %}
  <h1>My Google Login Project</h1>
  <a href="{% provider_login_url 'google' %}">Login with Google</a>
  {% endif %}

  </body>
</html>

user_login/templates/user_login/login.html
{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="/account/login/" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Login">

    </form>
{% endblock %}

user_login/templates/user_login/signup.html
{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/account/signup/" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">

    </form>
{% endblock %}